config/routes.rb
Rails.application.routes.draw do

  get '/api/v0/domains/map(.json)(/:extra)', to: 'api#map'
  get '/api/v0/process/:provider', to: 'api#xprocess'
  post '/api/v0/process/:provider', to: 'api#xprocess'

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, path: '/~admin~/users'

  concern :importable do
    collection do
      get :import
      post :import
    end
  end

  scope path: '/~admin~/' do

    resources :domain_configs, concerns: :importable do
      resources :replaces
      resources :cache_settings
      resources :subdomain_configs do
        resources :replaces
      end
    end
  end

  ActiveAdmin.routes(self)
  namespace :proxy_translator_admin do
    resources :settings

    resources :domain_configs do
      resources :subdomain_configs do
        resources :replaces
      end
    end

    resources :subdomain_configs do
      resources :replaces
    end

    resources :global_replacements do
      resources :replaces
    end
  end

  [
    ActiveAdmin::ResourceController,
    ActiveAdmin::Devise::SessionsController,
    ProxyTranslatorAdmin::DashboardController
  ].map do |skipped_class|
    skipped_class.class_eval do
      skip_authorization_check
    end
  end

  get '/~admin~', to: 'home#index', as: :admin_landing

  get '/:system(/*path)', to: 'proxy#system', system: /~.*?~/, format: false

  get '(*path).:format' => 'proxy#file', constraints: { format: /(css|js|png|jpg|jpeg|gif|svg|json|xml|ico|txt|eot|woff|ttf)/i }

  get '(*path)' => 'proxy#proxy', format: false

  match '*unmatched_route', :to => 'application#raise_not_found!', :via => :all
end

app/models/subdomain_config.rb
class SubdomainConfig < ActiveRecord::Base
  belongs_to :domain_config
  has_many :replaces, as: :replaceable

  validates_with DomainUniquenessValidator, on: :create
  validates :subdomain, format: { with: /\A[a-zA-Z]+\z/,
                                  message: I18n.t('subdomain.format') }

  def domain
    "#{subdomain}.#{domain_config.domain}"
  end

  delegate :user, to: :domain_config
end

app/controllers/subdomain_configs_controller.rb
class SubdomainConfigsController < ApplicationController
  load_and_authorize_resource :domain_config
  load_and_authorize_resource through: :domain_config
  # before_action :set_subdomain_config, only: [:show, :edit, :update, :destroy]
  before_action :init_parent

  # GET /subdomain_configs
  # GET /subdomain_configs.json
  def index
    # @subdomain_configs = SubdomainConfig.all
  end

  # GET /subdomain_configs/1
  # GET /subdomain_configs/1.json
  def show
  end

  # GET /subdomain_configs/new
  def new
    # @subdomain_config = SubdomainConfig.new
  end

  # GET /subdomain_configs/1/edit
  def edit
  end

  # POST /subdomain_configs
  # POST /subdomain_configs.json
  def create
    # @subdomain_config = SubdomainConfig.new(subdomain_config_params)

    respond_to do |format|
      if @subdomain_config.save
        format.html { redirect_to [@domain_config, @subdomain_config], notice: 'Subdomain config was successfully created.' }
        format.json { render :show, status: :created, location: @subdomain_config }
      else
        format.html { render :new }
        format.json { render json: @subdomain_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subdomain_configs/1
  # PATCH/PUT /subdomain_configs/1.json
  def update
    respond_to do |format|
      if @subdomain_config.update(subdomain_config_params)
        format.html { redirect_to [@domain_config, @subdomain_config], notice: 'Subdomain config was successfully updated.' }
        format.json { render :show, status: :ok, location: @subdomain_config }
      else
        format.html { render :edit }
        format.json { render json: @subdomain_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subdomain_configs/1
  # DELETE /subdomain_configs/1.json
  def destroy
    @subdomain_config.destroy
    respond_to do |format|
      format.html { redirect_to domain_config_subdomain_configs_url(@domain_config), notice: 'Subdomain config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subdomain_config
      # @subdomain_config = SubdomainConfig.find(params[:id])
    end

    def init_parent
      @parent_id = params[:domain_config_id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subdomain_config_params
      params.require(:subdomain_config).permit(:domain_config_id, :subdomain, :result_lang_code)
    end
end

app/helpers/subdomain_configs_helper.rb
module SubdomainConfigsHelper
end

app/views/subdomain_configs/_form.html.haml
= simple_form_for [@domain_config, @subdomain_config] do |f|
  = f.error_notification base: true
  .has-error= f.error :base

  .form-inputs
    = f.input :subdomain
    = f.input :result_lang_code

  .form-actions
    = f.button :submit

app/views/subdomain_configs/edit.html.haml
%h1 Editing subdomain_config

= render 'form'

= link_to [@domain_config, @subdomain_config] do
  %span.glyphicon.glyphicon-eye-open{:'aria-hidden' => 'true'}
\|
= link_to domain_config_subdomain_configs_path(@domain_config) do
  %span.glyphicon.glyphicon-circle-arrow-left{:'aria-hidden' => 'true'}

app/views/subdomain_configs/index.html.haml
%h1 Listing subdomain_configs

%table.table
  %thead
    %tr
      %th Domain config
      %th Subdomain
      %th Result lang code
      %th
      %th

  %tbody
    - @subdomain_configs.each do |subdomain_config|
      %tr
        %td= subdomain_config.domain_config_id
        %td= subdomain_config.subdomain
        %td= subdomain_config.result_lang_code
        %td= link_to 'Replacements', domain_config_subdomain_config_replaces_path(@domain_config, subdomain_config)
        %td
          = link_to [@domain_config, subdomain_config] do
            %span.glyphicon.glyphicon-eye-open{:'aria-hidden' => 'true'}
          = link_to edit_domain_config_subdomain_config_path(@domain_config, subdomain_config) do
            %span.glyphicon.glyphicon-pencil{:'aria-hidden' => 'true'}
          = link_to [@domain_config, subdomain_config], :method => :delete, :data => { :confirm => 'Are you sure?' } do
            %span.glyphicon.glyphicon-trash{:'aria-hidden' => 'true'}

%br

= link_to 'New Subdomain config', new_domain_config_subdomain_config_path(@parent_id)

app/views/subdomain_configs/new.html.haml
%h1 New subdomain_config

= render 'form'

= link_to domain_config_subdomain_configs_path(@domain_config) do
  %span.glyphicon.glyphicon-circle-arrow-left{:'aria-hidden' => 'true'}

app/views/subdomain_configs/show.html.haml
%p#notice= notice

%p
  %b Domain config:
  = @subdomain_config.domain_config_id
%p
  %b Subdomain:
  = @subdomain_config.subdomain
%p
  %b Result lang code:
  = @subdomain_config.result_lang_code

= link_to edit_domain_config_subdomain_config_path(@domain_config, @subdomain_config) do
  %span.glyphicon.glyphicon-pencil{:'aria-hidden' => 'true'}
\|
= link_to domain_config_subdomain_configs_path(@domain_config) do
  %span.glyphicon.glyphicon-circle-arrow-left{:'aria-hidden' => 'true'}