config/routes.rb
Rails.application.routes.draw do

  get '/api/v0/domains/map(.json)(/:extra)', to: 'api#map'
  get '/api/v0/process/:provider', to: 'api#xprocess'
  post '/api/v0/process/:provider', to: 'api#xprocess'

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, path: '/~admin~/users'

  concern :importable do
    collection do
      get :import
      post :import
    end
  end

  scope path: '/~admin~/' do

    resources :domain_configs, concerns: :importable do
      resources :replaces
      resources :cache_settings
      resources :subdomain_configs do
        resources :replaces
      end
    end
  end

  ActiveAdmin.routes(self)
  namespace :proxy_translator_admin do
    resources :settings

    resources :domain_configs do
      resources :subdomain_configs do
        resources :replaces
      end
    end

    resources :subdomain_configs do
      resources :replaces
    end

    resources :global_replacements do
      resources :replaces
    end
  end

  [
    ActiveAdmin::ResourceController,
    ActiveAdmin::Devise::SessionsController,
    ProxyTranslatorAdmin::DashboardController
  ].map do |skipped_class|
    skipped_class.class_eval do
      skip_authorization_check
    end
  end

  get '/~admin~', to: 'home#index', as: :admin_landing

  get '/:system(/*path)', to: 'proxy#system', system: /~.*?~/, format: false

  get '(*path).:format' => 'proxy#file', constraints: { format: /(css|js|png|jpg|jpeg|gif|svg|json|xml|ico|txt|eot|woff|ttf)/i }

  get '(*path)' => 'proxy#proxy', format: false

  match '*unmatched_route', :to => 'application#raise_not_found!', :via => :all
end

app/models/domain_config.rb
class DomainConfig < ActiveRecord::Base
  has_many :replaces, as: :replaceable
  has_many :cache_settings
  has_many :subdomain_configs, dependent: :destroy
  belongs_to :user

  validates_with DomainUniquenessValidator, on: :create
  validates :donor_url, uniqueness: true
  before_save :normalize_donor_url

  def to_s
    domain
  end

  def subdomains_count
    subdomain_configs.count
  end

  def normalize_donor_url
    url = self.donor_url
    url.strip!
    unless url.empty? || url[/\Ahttps?:\/\//]
      url = "http://#{url}"
    end

    uri = URI.parse(url)
    self.donor_url = "#{uri.scheme}://#{uri.host}"
  end

  def domain_link
    "http://#{domain}"
  end

end

app/controllers/domain_configs_controller.rb
class DomainConfigsController < ApplicationController
  # before_action :set_domain_config, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  include Importable

  # GET /domain_configs
  # GET /domain_configs.json
  def index
    # @domain_configs = DomainConfig.all
  end

  # GET /domain_configs/1
  # GET /domain_configs/1.json
  def show
  end

  # GET /domain_configs/new
  def new
    # @domain_config = DomainConfig.new
  end

  # GET /domain_configs/1/edit
  def edit
  end

  # POST /domain_configs
  # POST /domain_configs.json
  def create
    # @domain_config = DomainConfig.new(domain_config_params)

    @domain_config.user_id = current_user.id

    respond_to do |format|
      if @domain_config.save
        format.html { redirect_to @domain_config, notice: 'Domain config was successfully created.' }
        format.json { render :show, status: :created, location: @domain_config }
      else
        format.html { render :new }
        format.json { render json: @domain_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domain_configs/1
  # PATCH/PUT /domain_configs/1.json
  def update
    respond_to do |format|
      if @domain_config.update(domain_config_params)
        format.html { redirect_to @domain_config, notice: 'Domain config was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain_config }
      else
        format.html { render :edit }
        format.json { render json: @domain_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domain_configs/1
  # DELETE /domain_configs/1.json
  def destroy
    @domain_config.destroy
    respond_to do |format|
      format.html { redirect_to domain_configs_url, notice: 'Domain config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain_config
      @domain_config = DomainConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_config_params
      params.require(:domain_config).permit(:domain, :donor_url, :source_lang_code, :result_lang_code, :development_mode)
    end

    def importable
      {
          resource_class: DomainConfig,
          fields: [ :domain, :donor_url, :source_lang_code, :result_lang_code ],
          matchers: {
              user_id: current_user.id,
              domain: :domain
          }
      }
    end
end

app/helpers/domain_configs_helper.rb
module DomainConfigsHelper
end

app/views/domain_configs/_form.html.haml
= simple_form_for(@domain_config) do |f|
  = f.error_notification
  .has-error= f.error :base

  .form-inputs
    = f.input :domain
    = f.input :donor_url
    = f.input :source_lang_code
    = f.input :result_lang_code
    = f.input :development_mode

  .form-actions
    = f.button :submit

app/views/domain_configs/edit.html.haml
%h1 Editing domain_config

= render 'form'

= link_to @domain_config do
  %span.glyphicon.glyphicon-eye-open{:'aria-hidden' => 'true'}
\|
= link_to domain_configs_path do
  %span.glyphicon.glyphicon-circle-arrow-left{:'aria-hidden' => 'true'}

app/views/domain_configs/index.html.haml
%h1 Listing domain_configs

%table.table
  %thead
    %tr
      %th Domain
      %th Donor url
      %th Source lang code
      %th Result lang code
      %th
      %th
      %th
      %th

  %tbody
    - @domain_configs.each do |domain_config|
      %tr
        %td= domain_config.domain
        %td= domain_config.donor_url
        %td= domain_config.source_lang_code
        %td= domain_config.result_lang_code
        %td= link_to 'Subdomains', domain_config_subdomain_configs_path(domain_config)
        %td= link_to 'Replacements', domain_config_replaces_path(domain_config)
        %td= link_to 'Cache Settings', domain_config_cache_settings_path(domain_config)
        %td
          = link_to domain_config do
            %span.glyphicon.glyphicon-eye-open{:'aria-hidden' => 'true'}
          = link_to edit_domain_config_path(domain_config) do
            %span.glyphicon.glyphicon-pencil{:'aria-hidden' => 'true'}
          = link_to domain_config, :method => :delete, :data => { :confirm => 'Are you sure?' } do
            %span.glyphicon.glyphicon-trash{:'aria-hidden' => 'true'}

%br

= link_to 'New Domain config', new_domain_config_path
|
= link_to t('Import'), url_for(action: :import)

app/views/domain_configs/new.html.haml
%h1 New domain_config

= render 'form'

= link_to domain_configs_path do
  %span.glyphicon.glyphicon-circle-arrow-left{:'aria-hidden' => 'true'}

app/views/domain_configs/show.html.haml
%p#notice= notice

%p
  %b Domain:
  = @domain_config.domain
%p
  %b Donor url:
  = @domain_config.donor_url
%p
  %b Source lang code:
  = @domain_config.source_lang_code
%p
  %b Result lang code:
  = @domain_config.result_lang_code

= link_to edit_domain_config_path(@domain_config) do
  %span.glyphicon.glyphicon-pencil{:'aria-hidden' => 'true'}
\|
= link_to domain_configs_path do
  %span.glyphicon.glyphicon-circle-arrow-left{:'aria-hidden' => 'true'}