config/routes.rb
Rails.application.routes.draw do

  get '/api/v0/domains/map(.json)(/:extra)', to: 'api#map'
  get '/api/v0/process/:provider', to: 'api#xprocess'
  post '/api/v0/process/:provider', to: 'api#xprocess'

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, path: '/~admin~/users'

  concern :importable do
    collection do
      get :import
      post :import
    end
  end

  scope path: '/~admin~/' do

    resources :domain_configs, concerns: :importable do
      resources :replaces
      resources :cache_settings
      resources :subdomain_configs do
        resources :replaces
      end
    end
  end

  ActiveAdmin.routes(self)
  namespace :proxy_translator_admin do
    resources :settings

    resources :domain_configs do
      resources :subdomain_configs do
        resources :replaces
      end
    end

    resources :subdomain_configs do
      resources :replaces
    end

    resources :global_replacements do
      resources :replaces
    end
  end

  [
    ActiveAdmin::ResourceController,
    ActiveAdmin::Devise::SessionsController,
    ProxyTranslatorAdmin::DashboardController
  ].map do |skipped_class|
    skipped_class.class_eval do
      skip_authorization_check
    end
  end

  get '/~admin~', to: 'home#index', as: :admin_landing

  get '/:system(/*path)', to: 'proxy#system', system: /~.*?~/, format: false

  get '(*path).:format' => 'proxy#file', constraints: { format: /(css|js|png|jpg|jpeg|gif|svg|json|xml|ico|txt|eot|woff|ttf)/i }

  get '(*path)' => 'proxy#proxy', format: false

  match '*unmatched_route', :to => 'application#raise_not_found!', :via => :all
end

app/models/cache_setting.rb
class CacheSetting < ActiveRecord::Base
  belongs_to :domain_config

  # default cache time in seconds
  DEFAULT_CACHE_TIME = 1.hour
  DEFAULT_ASSETS_CACHE_TIME = 1.month

  def expire_after= (val)
    write_attribute :expire_after, ChronicDuration.parse(val, keep_zero: true)
  end

  def expire_after
    ChronicDuration.output read_attribute(:expire_after) || 0, format: :short, keep_zero: true
  end

  def expire_after_seconds
    read_attribute(:expire_after) || 0
  end
end

app/controllers/cache_settings_controller.rb
class CacheSettingsController < ApplicationController
  load_and_authorize_resource :domain_config
  load_and_authorize_resource through: :domain_config

  # GET /cache_settings
  # GET /cache_settings.json
  def index
  end

  # GET /cache_settings/1
  # GET /cache_settings/1.json
  def show
  end

  # GET /cache_settings/new
  def new
  end

  # GET /cache_settings/1/edit
  def edit
  end

  # POST /cache_settings
  # POST /cache_settings.json
  def create
    respond_to do |format|
      if @cache_setting.save
        format.html { redirect_to [@domain_config, @cache_setting], notice: 'Cache setting was successfully created.' }
        format.json { render :show, status: :created, location: @cache_setting }
      else
        format.html { render :new }
        format.json { render json: @cache_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cache_settings/1
  # PATCH/PUT /cache_settings/1.json
  def update
    respond_to do |format|
      if @cache_setting.update(cache_setting_params)
        format.html { redirect_to [@domain_config, @cache_setting], notice: 'Cache setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @cache_setting }
      else
        format.html { render :edit }
        format.json { render json: @cache_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cache_settings/1
  # DELETE /cache_settings/1.json
  def destroy
    @cache_setting.destroy
    respond_to do |format|
      format.html { redirect_to domain_config_cache_settings_url, notice: 'Cache setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def cache_setting_params
      params.require(:cache_setting).permit(:route_mask, :expire_after)
    end
end

app/helpers/cache_settings_helper.rb
module CacheSettingsHelper
end

app/views/cache_settings/_form.html.haml
= simple_form_for([@domain_config, @cache_setting]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :route_mask
    = f.input :expire_after, as: :string

  .form-actions
    = f.button :submit

app/views/cache_settings/edit.html.haml
%h1 Editing cache_setting

= render 'form'

= link_to [@domain_config, @cache_setting] do
  %span.glyphicon.glyphicon-eye-open{:'aria-hidden' => 'true'}
\|
= link_to domain_config_cache_setting_path do
  %span.glyphicon.glyphicon-circle-arrow-left{:'aria-hidden' => 'true'}

app/views/cache_settings/index.html.haml
%h1 Listing cache_settings

%table.table
  %thead
    %tr
      %th Route mask
      %th Expire after
      %th

  %tbody
    - @cache_settings.each do |cache_setting|
      %tr
        %td= cache_setting.route_mask
        %td= cache_setting.expire_after
        %td
          = link_to [@domain_config, cache_setting] do
            %span.glyphicon.glyphicon-eye-open{:'aria-hidden' => 'true'}
          = link_to edit_domain_config_cache_setting_path(@domain_config, cache_setting) do
            %span.glyphicon.glyphicon-pencil{:'aria-hidden' => 'true'}
          = link_to [@domain_config, cache_setting], :method => :delete, :data => { :confirm => 'Are you sure?' } do
            %span.glyphicon.glyphicon-trash{:'aria-hidden' => 'true'}

%br

= link_to 'New Cache setting', new_domain_config_cache_setting_path

app/views/cache_settings/new.html.haml
%h1 New cache_setting

= render 'form'

= link_to domain_config_cache_settings_path(@domain_config) do
  %span.glyphicon.glyphicon-circle-arrow-left{:'aria-hidden' => 'true'}

app/views/cache_settings/show.html.haml
%p#notice= notice

%p
  %b Route mask:
  = @cache_setting.route_mask
%p
  %b Expire after:
  = @cache_setting.expire_after

= link_to edit_domain_config_cache_setting_path(@domain_config, @cache_setting) do
  %span.glyphicon.glyphicon-pencil{:'aria-hidden' => 'true'}
\|
= link_to domain_config_cache_settings_path do
  %span.glyphicon.glyphicon-circle-arrow-left{:'aria-hidden' => 'true'}