config/routes.rb
Rails.application.routes.draw do

  get '/api/v0/domains/map(.json)(/:extra)', to: 'api#map'
  get '/api/v0/process/:provider', to: 'api#xprocess'
  post '/api/v0/process/:provider', to: 'api#xprocess'

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, path: '/~admin~/users'

  concern :importable do
    collection do
      get :import
      post :import
    end
  end

  scope path: '/~admin~/' do

    resources :domain_configs, concerns: :importable do
      resources :replaces
      resources :cache_settings
      resources :subdomain_configs do
        resources :replaces
      end
    end
  end

  ActiveAdmin.routes(self)
  namespace :proxy_translator_admin do
    resources :settings

    resources :domain_configs do
      resources :subdomain_configs do
        resources :replaces
      end
    end

    resources :subdomain_configs do
      resources :replaces
    end

    resources :global_replacements do
      resources :replaces
    end
  end

  [
    ActiveAdmin::ResourceController,
    ActiveAdmin::Devise::SessionsController,
    ProxyTranslatorAdmin::DashboardController
  ].map do |skipped_class|
    skipped_class.class_eval do
      skip_authorization_check
    end
  end

  get '/~admin~', to: 'home#index', as: :admin_landing

  get '/:system(/*path)', to: 'proxy#system', system: /~.*?~/, format: false

  get '(*path).:format' => 'proxy#file', constraints: { format: /(css|js|png|jpg|jpeg|gif|svg|json|xml|ico|txt|eot|woff|ttf)/i }

  get '(*path)' => 'proxy#proxy', format: false

  match '*unmatched_route', :to => 'application#raise_not_found!', :via => :all
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ProxyTranslator
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %body
      .navbar.navbar-default.navbar-static-top
        .container
          %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          -#%a.navbar-brand(href="#") Proxy Translate
          = link_to 'Proxy Translate', admin_landing_path, class: 'navbar-brand'
          .navbar-collapse.collapse.navbar-responsive-collapse
            %ul.nav.navbar-nav
              - if current_user
                %li
                  %a.dropdown-toggle{'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', :href => '#', :role => 'button'}
                    = current_user.email
                    %span.caret
                  %ul.dropdown-menu
                    %li= link_to 'Log Out', destroy_user_session_path, method: :delete
              -#%li= link_to "Link 2", "/path2"
              -#%li= link_to "Link 3", "/path3"
              -#%li= link_to "Link 3", "/path3"

      .container
        .row
          .col-lg-9
            = bootstrap_flash
            = yield
          -#.col-lg-3
            .well.sidebar-nav
              %h3 >>
              %ul.nav.nav-list
                %li.nav-header Welcome
                -#%li= link_to "Link 1", "/path1"
                -#%li= link_to "Link 2", "/path2"
                -#%li= link_to "Link 3", "/path3"

      %footer.footer
        .container
          %p.text-muted
            &copy; Proxy Translate
            = Date.today.year